import tensorflow as tf
from gan import GAN

# hyper parameters
BATCH_SIZE = 128
LR1 = 5e-5
LR2 = 2e-4
EPOCHS = 750
ALPHA = 5e-1

# Initialized the model with given hyperparameters
gan_model = GAN(BATCH_SIZE, LR1, LR2, ALPHA, EPOCHS)

# Load last trained model to skip training time
gan_model.load_model()
# Save generated_images.png to directory containing a 4x4 grid of images
# generated by the model.
gan_model.plot_generated_images('generated_images')
# Prints the generator, discriminator, and GAN model summary
gan_model.summary()
