"""
This file demonstrates how to use the GAN class to load a previously
trained model. To see an example of how to trian the model see training.py
"""
from gan import GAN


# Load last trained model to skip training time
gan_model = GAN()
gan_model.load_model()
# Save generated_images.png to directory containing a 4x4 grid of images
# generated by the model.
gan_model.plot_generated_images('generated_images')
# Prints the generator, discriminator, and GAN model summary
gan_model.summary()
